# Generated by Django 2.2.3 on 2019-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboxModel',
            fields=[
                ('senders', models.IntegerField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
            ],
        ),
    ]
