# Generated by Django 2.2.3 on 2019-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('org_id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=30)),
                ('org_address', models.TextField()),
                ('org_country', models.CharField(max_length=30)),
                ('org_state', models.CharField(max_length=20)),
                ('org_city', models.CharField(max_length=20)),
                ('org_email', models.EmailField(max_length=50)),
                ('org_password', models.CharField(max_length=10)),
                ('org_contact', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
