# Generated by Django 2.2.3 on 2019-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_organizationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=30)),
                ('donor_userid', models.CharField(max_length=30)),
                ('donor_password', models.CharField(max_length=30)),
                ('donor_gender', models.CharField(max_length=8)),
                ('donor_email', models.EmailField(max_length=50)),
                ('donor_contact', models.IntegerField(verbose_name=10)),
                ('donor_bloodgroup', models.CharField(max_length=2)),
                ('donor_state', models.CharField(max_length=20)),
                ('donor_city', models.CharField(max_length=20)),
                ('donor_age', models.IntegerField(verbose_name=2)),
                ('donor_weight', models.IntegerField(verbose_name=2)),
                ('donor_donatedate', models.DateField()),
            ],
        ),
    ]
